'use client'

import React, { useRef } from 'react';
import { motion } from 'framer-motion';
import { Shield, Eye, Lock, Users, Brain, CheckCircle, AlertCircle, TrendingUp, FileText, Database } from 'lucide-react';

export default function AIPrinciples() {
  const containerRef = useRef(null);

  return (
    <div ref={containerRef} className="bg-white text-gray-900">
      <style jsx>{`
        .text-navy {
          color: #1e293b;
        }
        
        .bg-navy {
          background-color: #1e293b;
        }
        
        .text-orange {
          color: #ea580c;
        }
        
        .bg-orange {
          background-color: #ea580c;
        }
        
        .hover-lift {
          transition: transform 0.3s ease, box-shadow 0.3s ease;
        }
        
        .hover-lift:hover {
          transform: translateY(-4px);
          box-shadow: 0 12px 24px rgba(0, 0, 0, 0.08);
        }

        @keyframes subtle-pulse {
          0%, 100% { opacity: 0.2; }
          50% { opacity: 0.4; }
        }

        .animate-ai {
          animation: subtle-pulse 4s ease-in-out infinite;
        }
      `}</style>

      {/* Hero Section */}
      <section className="min-h-screen flex items-center justify-center px-4 sm:px-6 md:px-8 py-12 sm:py-16 md:py-20 relative overflow-hidden">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-20 left-10 w-64 h-64 bg-orange/5 rounded-full blur-3xl animate-ai" />
          <div className="absolute bottom-20 right-10 w-80 h-80 bg-orange/5 rounded-full blur-3xl animate-ai" style={{ animationDelay: '2s' }} />
        </div>

        <div className="max-w-5xl mx-auto text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.25, 0.1, 0.25, 1] }}
          >
            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl font-semibold text-navy mb-6 sm:mb-8 leading-[1.15] sm:leading-[1.1] tracking-tight px-4">
              Responsible AI,<br className="hidden sm:block" />
              <span className="sm:inline"> </span>Built with Purpose
            </h1>
            
            <p className="text-base sm:text-lg font-semibold text-orange mb-6 sm:mb-8">
              Our Commitment to Ethical Intelligence
            </p>
            
            <p className="text-lg sm:text-xl md:text-2xl text-gray-600 mb-8 sm:mb-10 md:mb-12 max-w-3xl mx-auto leading-relaxed font-normal px-4">
              SurFox Infinity is powerful technology. These principles guide how we build it, deploy it, and use it to serve our customers.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Core Principles */}
      <section className="py-20 sm:py-32 md:py-40 px-4 sm:px-6 md:px-8 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16 sm:mb-20 md:mb-24"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-navy mb-4 sm:mb-6 px-4">
              Our Core AI Principles
            </h2>
            <p className="text-lg sm:text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed px-4">
              The non-negotiable values that govern every decision we make
            </p>
          </motion.div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 sm:gap-10 md:gap-12 px-4">
            {[
              { 
                icon: Lock,
                number: '01',
                title: 'Data Privacy is Sacred', 
                desc: 'Your data remains yours. Complete tenant isolation means no cross-customer learning, no data sharing, no exceptions. We don\'t train our models on your proprietary information.',
                commitment: 'Every tenant operates in a completely isolated environment with encrypted data boundaries.'
              },
              { 
                icon: Eye,
                number: '02',
                title: 'Transparency Over Black Boxes', 
                desc: 'We explain how SurFox reaches conclusions. No mysterious "AI magic" — our predictive models use traceable logic and statistical reasoning that can be understood and audited.',
                commitment: 'Customers can request explanations for any prediction or score generated by the platform.'
              },
              { 
                icon: Users,
                number: '03',
                title: 'Human-in-the-Loop', 
                desc: 'AI augments human judgment, never replaces it. SurFox provides intelligence and recommendations, but humans make the final decisions on actions that affect people.',
                commitment: 'Critical decisions require human review and approval — the AI suggests, humans decide.'
              },
              { 
                icon: Shield,
                number: '04',
                title: 'Bias Detection & Mitigation', 
                desc: 'We actively monitor for algorithmic bias in our models. When patterns emerge that could lead to unfair outcomes, we investigate and correct them.',
                commitment: 'Regular audits of model outputs across demographic segments to identify and address bias.'
              },
              { 
                icon: TrendingUp,
                number: '05',
                title: 'Continuous Improvement', 
                desc: 'AI ethics isn\'t static. As we learn more about responsible AI practices, we evolve our approach. We commit to staying current with research and best practices.',
                commitment: 'Annual review of AI principles with updates based on new learnings and industry standards.'
              },
              { 
                icon: FileText,
                number: '06',
                title: 'Clear Use Case Boundaries', 
                desc: 'We\'re explicit about what SurFox should and shouldn\'t be used for. Our technology is designed for business intelligence, not surveillance or manipulation.',
                commitment: 'Acceptable use policies prohibit harmful applications and are enforced in our terms of service.'
              }
            ].map((principle, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: i * 0.1 }}
                className="bg-white rounded-2xl border-2 border-gray-200 p-8 sm:p-10 hover:border-orange/30 hover:shadow-xl transition-all duration-300"
              >
                <div className="flex items-start gap-4 mb-6">
                  <div className="w-14 h-14 rounded-xl bg-orange/10 flex items-center justify-center flex-shrink-0">
                    <principle.icon className="w-7 h-7 text-orange" />
                  </div>
                  <div className="text-5xl font-bold text-gray-100">{principle.number}</div>
                </div>
                
                <h3 className="text-xl sm:text-2xl font-semibold text-navy mb-3">{principle.title}</h3>
                <p className="text-gray-700 leading-relaxed mb-4">{principle.desc}</p>
                
                <div className="bg-orange/5 border-l-4 border-orange rounded-lg p-4">
                  <p className="text-sm font-medium text-gray-600">
                    <span className="text-orange font-semibold">Our Commitment:</span> {principle.commitment}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* What We Don't Do */}
      <section className="py-20 sm:py-32 md:py-40 px-4 sm:px-6 md:px-8 bg-white">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16 sm:mb-20 md:mb-24"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-navy mb-4 sm:mb-6 px-4">
              What We Don't Do
            </h2>
            <p className="text-lg sm:text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed px-4">
              Clear boundaries on how SurFox should never be used
            </p>
          </motion.div>
          
          <div className="max-w-4xl mx-auto px-4 space-y-6">
            {[
              { 
                title: 'No Cross-Customer Data Mining',
                desc: 'We will never aggregate data across customers to build "industry benchmarks" or "collective intelligence" without explicit opt-in consent. Your patterns stay yours.'
              },
              { 
                title: 'No Emotional Manipulation',
                desc: 'SurFox analyzes sentiment and intent to help businesses understand customers — not to manipulate emotional responses or exploit psychological vulnerabilities.'
              },
              { 
                title: 'No Deceptive Automation',
                desc: 'When SurFox assists with communication, it\'s transparent. We don\'t enable bots pretending to be humans or automated systems designed to deceive.'
              },
              { 
                title: 'No Discriminatory Practices',
                desc: 'Our models cannot be configured to explicitly discriminate based on protected characteristics. We monitor for proxy discrimination patterns.'
              },
              { 
                title: 'No Surveillance Applications',
                desc: 'SurFox is built for business intelligence, not employee surveillance. We don\'t enable monitoring that violates reasonable privacy expectations.'
              },
              { 
                title: 'No Model Training on Your Data',
                desc: 'We don\'t use your proprietary data to train foundation models that serve other customers. Your competitive intelligence remains exclusively yours.'
              }
            ].map((item, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="bg-white p-6 rounded-xl border border-red-200 hover:border-red-300 hover:shadow-md transition-all duration-300"
              >
                <div className="flex items-start gap-4">
                  <div className="w-6 h-6 rounded-full bg-red-100 flex items-center justify-center flex-shrink-0 mt-0.5">
                    <AlertCircle className="w-4 h-4 text-red-600" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-navy mb-2">{item.title}</h3>
                    <p className="text-gray-600 leading-relaxed">{item.desc}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How We Build Responsibly */}
      <section className="py-20 sm:py-32 md:py-40 px-4 sm:px-6 md:px-8 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16 sm:mb-20 md:mb-24"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-navy mb-4 sm:mb-6 px-4">
              How We Build Responsibly
            </h2>
            <p className="text-lg sm:text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed px-4">
              Principles guide strategy, practices ensure execution
            </p>
          </motion.div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 sm:gap-10 md:gap-12 px-4">
            {[
              { 
                icon: Database,
                title: 'Data Governance', 
                desc: 'Strict protocols for data handling, retention, and deletion. Regular audits ensure compliance with privacy commitments.',
                practices: ['Encrypted at rest & in transit', 'Automatic data retention policies', 'Secure deletion on request']
              },
              { 
                icon: Brain,
                title: 'Model Development', 
                desc: 'Rigorous testing before deployment. Models are evaluated for accuracy, fairness, and potential unintended consequences.',
                practices: ['Bias testing across segments', 'Performance monitoring', 'Fallback to human judgment']
              },
              { 
                icon: FileText,
                title: 'Documentation', 
                desc: 'Clear documentation of how models work, what data they use, and how predictions are generated.',
                practices: ['Model cards for transparency', 'Data source documentation', 'Explainability features']
              }
            ].map((item, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: i * 0.1 }}
                className="bg-white p-6 sm:p-8 rounded-2xl border border-gray-200 hover:border-orange/30 hover:shadow-lg transition-all duration-300"
              >
                <div className="w-12 h-12 sm:w-14 sm:h-14 rounded-xl bg-orange/10 flex items-center justify-center mb-5">
                  <item.icon className="w-6 h-6 sm:w-7 sm:h-7 text-orange" />
                </div>
                
                <h3 className="text-lg sm:text-xl font-semibold text-navy mb-3">{item.title}</h3>
                <p className="text-gray-600 leading-relaxed mb-4">{item.desc}</p>
                
                <div className="space-y-2">
                  {item.practices.map((practice, idx) => (
                    <div key={idx} className="flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-green-600 flex-shrink-0" />
                      <span className="text-sm text-gray-600">{practice}</span>
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Customer Rights */}
      <section className="py-20 sm:py-32 md:py-40 px-4 sm:px-6 md:px-8 bg-white">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16 sm:mb-20 md:mb-24"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-navy mb-4 sm:mb-6 px-4">
              Your Rights as a Customer
            </h2>
            <p className="text-lg sm:text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed px-4">
              What you can expect from us
            </p>
          </motion.div>
          
          <div className="max-w-4xl mx-auto bg-white rounded-2xl border-2 border-gray-200 p-8 sm:p-10 md:p-12">
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <div className="w-8 h-8 rounded-lg bg-green-100 flex items-center justify-center flex-shrink-0 mt-1">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-navy mb-2">Right to Explanation</h3>
                  <p className="text-gray-600 leading-relaxed">
                    You can request an explanation for any prediction, score, or recommendation made by SurFox. We'll explain the factors that influenced the output.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-8 h-8 rounded-lg bg-green-100 flex items-center justify-center flex-shrink-0 mt-1">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-navy mb-2">Right to Data Portability</h3>
                  <p className="text-gray-600 leading-relaxed">
                    Your data is yours to take. Export your data at any time in standard formats. No lock-in, no games.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-8 h-8 rounded-lg bg-green-100 flex items-center justify-center flex-shrink-0 mt-1">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-navy mb-2">Right to Deletion</h3>
                  <p className="text-gray-600 leading-relaxed">
                    Request permanent deletion of your data from SurFox systems. We comply within 30 days and provide confirmation.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-8 h-8 rounded-lg bg-green-100 flex items-center justify-center flex-shrink-0 mt-1">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-navy mb-2">Right to Human Review</h3>
                  <p className="text-gray-600 leading-relaxed">
                    Challenge automated decisions that significantly impact your business. Request human review of any AI-generated output.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-8 h-8 rounded-lg bg-green-100 flex items-center justify-center flex-shrink-0 mt-1">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-navy mb-2">Right to Opt-Out</h3>
                  <p className="text-gray-600 leading-relaxed">
                    Disable specific AI features if they don't align with your values. Use SurFox in ways that work for your organization.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Accountability */}
      <section className="py-20 sm:py-32 md:py-40 px-4 sm:px-6 md:px-8 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16 sm:mb-20"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-navy mb-4 sm:mb-6 px-4">
              Accountability & Oversight
            </h2>
            <p className="text-lg sm:text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed px-4">
              How we ensure we live up to these principles
            </p>
          </motion.div>

          <div className="max-w-4xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="bg-white rounded-2xl border border-gray-200 p-8 sm:p-10 md:p-12"
            >
              <div className="space-y-6">
                <p className="text-lg text-gray-700 leading-relaxed">
                  These principles aren't marketing copy — they're operational commitments. We hold ourselves accountable through:
                </p>

                <ul className="space-y-4">
                  <li className="flex items-start gap-3">
                    <div className="w-2 h-2 rounded-full bg-orange mt-2 flex-shrink-0"></div>
                    <p className="text-gray-700 leading-relaxed">
                      <strong className="text-navy">Regular Internal Audits:</strong> Quarterly reviews of AI system outputs to identify bias, errors, or unintended consequences.
                    </p>
                  </li>
                  <li className="flex items-start gap-3">
                    <div className="w-2 h-2 rounded-full bg-orange mt-2 flex-shrink-0"></div>
                    <p className="text-gray-700 leading-relaxed">
                      <strong className="text-navy">Customer Feedback Loops:</strong> Direct channels for reporting concerns about AI behavior, with mandatory investigation and response.
                    </p>
                  </li>
                  <li className="flex items-start gap-3">
                    <div className="w-2 h-2 rounded-full bg-orange mt-2 flex-shrink-0"></div>
                    <p className="text-gray-700 leading-relaxed">
                      <strong className="text-navy">Third-Party Security Audits:</strong> Pursuing SOC 2 Type II and ISO 27001 certification for independent verification of data isolation and privacy controls.
                    </p>
                  </li>
                  <li className="flex items-start gap-3">
                    <div className="w-2 h-2 rounded-full bg-orange mt-2 flex-shrink-0"></div>
                    <p className="text-gray-700 leading-relaxed">
                      <strong className="text-navy">Transparent Updates:</strong> When we update these principles or discover new ethical considerations, we communicate changes to customers.
                    </p>
                  </li>
                </ul>

                <div className="bg-orange/5 border-l-4 border-orange rounded-lg p-6 mt-8">
                  <p className="text-lg font-semibold text-navy mb-2">
                    Have concerns about how SurFox handles AI?
                  </p>
                  <p className="text-gray-700 leading-relaxed">
                    We want to hear from you. Contact our ethics team at <a href="mailto:ethics@getsurfox.com" className="text-orange font-semibold hover:underline">ethics@getsurfox.com</a>
                  </p>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Closing Section */}
      <section className="py-20 sm:py-28 md:py-32 px-4 sm:px-6 md:px-8 bg-gradient-to-b from-white to-gray-50">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-navy mb-6 sm:mb-8 px-4 leading-tight">
              Principles in Practice
            </h2>
            
            <p className="text-lg sm:text-xl text-gray-600 mb-10 sm:mb-12 leading-relaxed px-4 max-w-3xl mx-auto">
              These aren't aspirational statements — they're how we operate every day. Building powerful AI comes with responsibility, and we take that seriously.
            </p>

            <p className="text-base sm:text-lg font-semibold text-orange px-4">
              Intelligence with integrity. That's the SurFox way.
            </p>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
